import { Course } from "../course/Course";
import { parseISO } from "date-fns";

//Parsing the calendar data (mostly generated by Github copilot)
export function parseCalendar(data: string): Array<Course> {
    let courses: Array<Course> = new Array<Course>();
    let lines: Array<string> = data.split("\r");
    let course: Course | null = null;

    //Parsing the data line by line
    for (let i = 0; i < lines.length; i++) {
        let line: string = lines[i].trim();

        //If the line is a course
        if (line.startsWith("BEGIN:VEVENT")) {
            course = new Course("", "", new Date(), new Date(), "");
        }
        //If the line is the end of a course
        else if (line.startsWith("END:VEVENT")) {
            if (course != null)
                courses.push(course);
        }
        //If the line is the name of a course
        else if (line.startsWith("SUMMARY:")) {
            if (course != null)
                course.name = line.substring(8);
        }
        //If the line is the start date of a course
        else if (line.startsWith("DTSTART:")) {
            if (course != null)
                course.startDate = parseISO(line.substring(8));
        }
        //If the line is the end date of a course
        else if (line.startsWith("DTEND:")) {
            if (course != null)
                course.endDate = parseISO(line.substring(6));
        }
        //If the line is the location of a course
        else if (line.startsWith("LOCATION:")) {
            if (course != null)
                course.location = line.substring(9);
        }
    }

    return courses;
}

